<?php
/**
 * @file
 * Aloha Editor
 */
function alohaeditor_menu() {
	$items['alohaeditor/lookup/%'] = array(
		'page callback' => 'alohaeditor_lookup',
		'page arguments' => array(2),
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	return $items;
}

function alohaeditor_lookup($lookup = false) {
	$lookup = check_plain($lookup);

	$search_results = node_search_execute($lookup);
	//watchdog('aloha editor', 'search results: '.print_r($search_results, true));

	if (is_array($search_results) && empty($search_results[0])) {
		$search_results = false;
	}

	header('Content-Type:text/javascript');
	if (is_array($search_results)) {
		$out = '[';
		foreach ($search_results as $result) {
			$out .= '{"u":"'.$result['link'].'","d":"'.$result['title'].'","a":"","t":[""],"dt":"","n":""},';
		}
		$out = substr($out, 0, -1);
		$out .= ']';
		echo $out;
	} else {
		echo '[]';
	}
}